# -*- coding: utf-8 -*-
"""Cluster Analysis KMeans (Bindu Miss) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXl5kpXlyin_b9fOuu-12YfuuDEEVO8t
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram,linkage
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples,silhouette_score

data=pd.read_excel('/content/Cluster_Analysis_Example.xlsx')

data.head()

data.info()

data.isnull().sum()

data.describe()

#Removing unwanted columns
data=data.iloc[:,1:7]
data.head()

#Hierachical Clustering
Linkage=linkage(data,'ward')
Linkage

#Dendrogram
plt.figure(figsize=(10,5))
dendrogram(Linkage,orientation='top',distance_sort='descending',show_leaf_counts=True)
plt.title('Dendrogram')
plt.xlabel('Records')
plt.ylabel('Distance')
plt.show()

"""K Mean Clustering"""

#Non Heirarchical Clustering
model=KMeans(n_clusters=3)

#To fix KMeans into the data
model=model.fit(data)

#To identify cluster id of each item
cluster_id=model.predict(data)
cluster_id

"""Values 0,1,2 means cluster 1,2,3

The first value '2' (ie,Cluster 2) means the first Customer or item go to Cluster 2

The Second value '0' (ie,Cluster 3) means the second Customer or item go to Cluster 3

The first value '2' (ie,Cluster 1) means the third Customer or item go to Cluster 1


"""

#Making cluste rid as data frame
cluster_id=pd.DataFrame(cluster_id,columns=['Cluster ID'])
cluster_id.head()

#Joining Cluster id with the original data
result=data.join(cluster_id)
result.head()

#Computing cluster centeroid
clusters=model.cluster_centers_
clusters=pd.DataFrame(clusters)
clusters

#Performance Measures - (overall average) Silhouette width
cluster_id=model.predict(data)
silhouette_avg=silhouette_score(data,cluster_id)
silhouette_avg

#Indivituall silhouette width
silhoutte_values=silhouette_samples(data,cluster_id)
silhouette_values=pd.DataFrame(silhoutte_values)
silhouette_values.head()

#Another Cluster Performance Measure
Sum_of_squared_distance=[]
K=range(1,8)
for k in K:
  model=KMeans(n_clusters=k)
  model=model.fit(data)
  Sum_of_squared_distance.append(model.inertia_)
plt.plot(K,Sum_of_squared_distance,'bx-')
plt.xlabel('Number of cluster')
plt.ylabel('Sum of Squared Distance')
plt.grid()
plt.show()

